services:
  - type: web
    name: lastminutecamps-python-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: RECREATION_GOV_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
